# Generated by Django 4.1.2 on 2022-10-20 10:35

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_img', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tweet_table',
            },
        ),
    ]
