# Generated by Django 4.1.1 on 2022-10-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TweetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_img", models.ImageField(null=True, upload_to="images/")),
                ("upload_label_img", models.ImageField(upload_to="images/")),
                ("category", models.CharField(max_length=256)),
            ],
            options={"db_table": "tweet_table",},
        ),
    ]
